const List<String> modelNames = [
  'toyota, sienna',
  'jeep, cherokee',
  'ford, focus',
  'honda, civic',
  'honda, accord',
  'ford, mustang',
  'chevrolet, camaro',
  'chevrolet, corvette',
  'toyota, rav4',
  'toyota, camry',
  'toyota, corolla',
  'mercedes-benz, g-class',
  'mercedes-benz, s-class',
  'mercedes-benz, amg',
  'bmw, 3',
  'series',
  'bmw, 5',
  'series',
  'bmw, m3',
  'bmw, x3',
  'porsche, 911',
  'tesla, modelX',
  'tesla, modelY',
  'tesla, model3',
  'tesla, modelS',
];
